version: '3.8'

services:
  db:
    image: postgres:16 # 최신 버전의 포스트그레스 이미지 사용
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
