[build]
builder = "NIXPACKS"
buildCommand = "rm -rf node_modules && rm -rf dist && npm install && npm run build"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"

[healthcheck]
path = "/health"
timeout = 300